#ifndef __OTA_MODULE_CONFIG_H__
#define __OTA_MODULE_CONFIG_H__

#define OTA_IS_HAVE_FACTORY_APP     0
#define OTA_IS_DUAL_APP             0
#define OTA_APP_MAX_VERIFY_COUNT    3

#define OTA_PLATFORM_FLASH_BASE             0x08000000
#define OTA_PLATFORM_FLASH_SIZE             (512 * 1024)
#define OTA_PLATFORM_FLASH_PAGE_SIZE        (FLASH_PAGE_SIZE)
#define OTA_PLATFORM_RECORD_ADDR            (OTA_PLATFORM_FLASH_BASE + (56 * 1024))
#define OTA_PLATFORM_RECORD_SIZE            (4 * 1024)
#define OTA_PLATFORM_RESERVED_SIZE          (4 * 1024)
#define OTA_PLATFORM_APP_PARTITION_SIZE     (448 * 1024)
#define OTA_PLATFORM_APP1_ADDR              (OTA_PLATFORM_RECORD_ADDR + OTA_PLATFORM_RECORD_SIZE + OTA_PLATFORM_RESERVED_SIZE)
// #define OTA_PLATFORM_APP2_ADDR              (OTA_PLATFORM_APP1_ADDR + OTA_PLATFORM_APP_PARTITION_SIZE)

#endif /* __OTA_MODULE_CONFIG_H__ */
