#!/bin/bash
set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo "========================================="
echo "  NE503 Platform Dev Environment"
echo "========================================="
echo ""
echo -e "${CYAN}Tools:${NC}"
echo -e "  Go:          $(go version 2>/dev/null | awk '{print $3}' || echo 'not found')"
echo -e "  Node.js:     $(node --version 2>/dev/null || echo 'not found')"
echo -e "  pnpm:        $(pnpm --version 2>/dev/null || echo 'not found')"
echo -e "  protoc:      $(protoc --version 2>/dev/null || echo 'not found')"
echo -e "  cmake:       $(cmake --version 2>/dev/null | head -1 || echo 'not found')"
echo -e "  g++:         $(g++ --version 2>/dev/null | head -1 || echo 'not found')"
echo -e "  Python:      $(python3 --version 2>/dev/null || echo 'not found')"
echo -e "  QEMU:        $(qemu-aarch64-static --version 2>&1 | head -1 || echo 'not found')"
echo ""

# ── SDK check ─────────────────────────────────────────────────────────────────
SDK_DIR="${HAILO_SDK_PATH:-/opt/hailo-sdk}"
HAS_SDK=false
if [ -d "$SDK_DIR" ] && [ -f "$SDK_DIR/environment-setup-"*"-poky-linux" ] 2>/dev/null; then
    POKY_ENV=$(find "$SDK_DIR" -name "environment-setup-*-poky-linux" -type f 2>/dev/null | head -1)
    if [ -n "$POKY_ENV" ]; then
        echo -e "${GREEN}Hailo SDK: ${SDK_DIR}${NC}"
        echo -e "${GREEN}Poky env:  ${POKY_ENV}${NC}"
        HAS_SDK=true
    fi
else
    echo -e "${YELLOW}Hailo SDK not found. ARM cross-compile unavailable.${NC}"
fi

# ── Source code check ─────────────────────────────────────────────────────────
echo ""
PROJECT_DIR=""
if [ -f "$HOME/ne503/Makefile" ]; then
    PROJECT_DIR="$HOME/ne503"
elif [ -f "/ne503/Makefile" ]; then
    PROJECT_DIR="/ne503"
fi

if [ -n "$PROJECT_DIR" ]; then
    echo -e "${GREEN}Source code: ${PROJECT_DIR}${NC}"
    cd "$PROJECT_DIR"

    # ── Auto-configure Makefile.docker for built-in SDK ────────────────────────
    if [ "$HAS_SDK" = true ]; then
        # Detect if existing Makefile.local points to wrong SDK path
        NEED_DOCKER_OVERRIDE=false
        if [ -f Makefile.local ]; then
            LOCAL_SDK=$(grep '^SDK_PATH=' Makefile.local 2>/dev/null | cut -d= -f2)
            if [ -n "$LOCAL_SDK" ] && [ ! -d "$LOCAL_SDK" ]; then
                NEED_DOCKER_OVERRIDE=true
            fi
        fi

        # Always ensure Makefile.docker exists and points to the container's SDK.
        # Makefile.local (if present) will override it — that's intentional:
        # the Makefile includes Makefile.docker first, then Makefile.local last.
        # On mount mode, the host Makefile.local may point to a path that doesn't
        # exist inside the container; patch SDK_PATH in Makefile.local too.
        if [ ! -f Makefile.docker ] || [ "$NEED_DOCKER_OVERRIDE" = true ]; then
            echo -e "${GREEN}Writing Makefile.docker (SDK=${SDK_DIR}, HAL_PLATFORM=hailo15)${NC}"
            cat > Makefile.docker <<EOF
# Auto-generated by NE503 Docker dev environment
SDK_PATH=${SDK_DIR}
HAL_PLATFORM=hailo15
EOF
            # Fix Makefile.local's SDK_PATH if it points to a path
            # that doesn't exist inside this container (e.g. host-only path).
            if [ -f Makefile.local ] && [ "$NEED_DOCKER_OVERRIDE" = true ]; then
                echo -e "${YELLOW}Patching Makefile.local SDK_PATH → ${SDK_DIR} (container override)${NC}"
                sed -i "s|^SDK_PATH=.*|SDK_PATH=${SDK_DIR}|" Makefile.local
            fi
        fi

        # ── Auto-generate CMake toolchain file for hailo15 cross-compilation ────
        TOOLCHAIN_FILE="cmake/toolchain-aarch64-hailo.cmake"
        if [ -d hal_v2 ] && [ ! -f "$TOOLCHAIN_FILE" ]; then
            echo -e "${GREEN}Generating ${TOOLCHAIN_FILE} from SDK environment${NC}"
            mkdir -p cmake
            SYSROOT="${SDK_DIR}/sysroots/armv8a-poky-linux"
            # ARM64 host: x86_64 SDK cross-compiler runs via QEMU binfmt_misc
            NATIVE_SYSROOT="${SDK_DIR}/sysroots/x86_64-pokysdk-linux"
            TOOLCHAIN_BINDIR="${NATIVE_SYSROOT}/usr/bin/aarch64-poky-linux"
            PREFIX="aarch64-poky-linux"
            cat > "$TOOLCHAIN_FILE" <<TCEOF
# Auto-generated by NE503 Docker dev environment from ${POKY_ENV}
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(OECORE_NATIVE_SYSROOT "${NATIVE_SYSROOT}")
set(OECORE_TARGET_SYSROOT "${SYSROOT}")

set(TOOLCHAIN_PREFIX "${PREFIX}")
set(TOOLCHAIN_BINDIR "\${OECORE_NATIVE_SYSROOT}/usr/bin/\${TOOLCHAIN_PREFIX}")

set(CMAKE_C_COMPILER   "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-g++")
set(CMAKE_AR           "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-ar")
set(CMAKE_RANLIB       "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-ranlib")
set(CMAKE_STRIP        "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-strip")
set(CMAKE_NM           "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-nm")
set(CMAKE_OBJCOPY      "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-objcopy")
set(CMAKE_OBJDUMP      "\${TOOLCHAIN_BINDIR}/\${TOOLCHAIN_PREFIX}-objdump")

set(CMAKE_SYSROOT "\${OECORE_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "\${OECORE_TARGET_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "-mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=\${OECORE_TARGET_SYSROOT}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_INIT "-mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=\${OECORE_TARGET_SYSROOT}" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now" CACHE STRING "")
TCEOF
        fi
    fi

    echo ""
    echo -e "${CYAN}Build commands:${NC}"
    echo "  make env-check          # verify toolchain"
    echo "  make layer1             # proto + Go + web + Python SDK"
    echo "  make layer2             # + stub HAL + camera-daemon"
    echo "  make pack-release       # package firmware (ARM cross-compile + tarball)"
else
    echo -e "${YELLOW}No source code found.${NC}"
    echo ""
    echo -e "${CYAN}Get started:${NC}"
    echo "  git clone <repo-url> ~/ne503"
    echo "  cd ~/ne503"
    echo "  make layer1             # build proto + Go services + web"
    echo "  make pack-release       # package firmware"
    echo ""
    echo -e "${CYAN}Or mount from host:${NC}"
    echo "  docker run -it -v /path/to/ne503:/ne503 ne503-dev-env"
fi

echo ""
echo "========================================="
echo ""

exec "$@"
