// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDeviceNetworkConfig(arg1:string):Promise<main.NetworkConfig>;

export function GetDevices():Promise<Array<main.DeviceItem>>;

export function GetListenerStats():Promise<main.ListenerStats>;

export function GetNetworkInterfaces():Promise<Array<string>>;

export function GetSettings():Promise<main.Settings>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function Ping():Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;

export function ScanDevices(arg1:string):Promise<string>;

export function SendCommand(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetDeviceNetworkConfig(arg1:string,arg2:string):Promise<string>;

export function StartDiscovery(arg1:string):Promise<string>;

export function StopDiscovery():Promise<void>;
