// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseRecordFile(arg1) {
  return window['go']['main']['App']['ChooseRecordFile'](arg1);
}

export function GetDefaultRecordPath(arg1) {
  return window['go']['main']['App']['GetDefaultRecordPath'](arg1);
}

export function GetDeviceNetworkConfig(arg1) {
  return window['go']['main']['App']['GetDeviceNetworkConfig'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetListenerStats() {
  return window['go']['main']['App']['GetListenerStats']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetRecordHistory() {
  return window['go']['main']['App']['GetRecordHistory']();
}

export function GetRecordStatus() {
  return window['go']['main']['App']['GetRecordStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ProbeManualDevice(arg1) {
  return window['go']['main']['App']['ProbeManualDevice'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanDevices(arg1) {
  return window['go']['main']['App']['ScanDevices'](arg1);
}

export function SendCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2, arg3);
}

export function SetDeviceNetworkConfig(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceNetworkConfig'](arg1, arg2);
}

export function StartDiscovery(arg1) {
  return window['go']['main']['App']['StartDiscovery'](arg1);
}

export function StartMetricsRecording(arg1) {
  return window['go']['main']['App']['StartMetricsRecording'](arg1);
}

export function StopDiscovery() {
  return window['go']['main']['App']['StopDiscovery']();
}

export function StopMetricsRecording() {
  return window['go']['main']['App']['StopMetricsRecording']();
}
